#ifndef BIGI_CUSTOM_VARIANTS_PRAGMA
#define BIGI_CUSTOM_VARIANTS_PRAGMA

#pragma shader_feature_local_fragment NORMAL_MAPPING
#pragma shader_feature_local_fragment MULTI_TEXTURE
#pragma shader_feature_local_fragment LTCGI_ENABLED
#pragma shader_feature_local DO_ALPHA_PLS
#pragma shader_feature_local_fragment SPECSMOOTH_MAP_ENABLED
#pragma shader_feature_local_fragment PROTV_SQUARE_ENABLED
#pragma shader_feature_local_fragment DECAL_1_ENABLED
#pragma shader_feature_local_fragment DECAL_2_ENABLED
#pragma shader_feature_local_fragment DECAL_3_ENABLED

#endif